# Generated by Django 2.1 on 2020-02-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankJobs_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('total_vacancies', models.IntegerField()),
            ],
        ),
    ]
