# Generated by Django 2.1 on 2020-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovtJobApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Railwayjobs_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('total_vacancies', models.IntegerField()),
            ],
        ),
    ]
